server:
  port: 9001
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/tool?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 4599960
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池母子
      pool-name: Hikari
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 5000
      connection-test-query: SELECT 1

  redis:
    database: 1
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-active: 8
  servlet:
    multipart:
      max-request-size: 400MB
      max-file-size: 400MB
  jackson:
      date-format: com.ner.common.CommDateFormat
      default-property-inclusion: non_null
      time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.ner.*.model,com.ner.*.entity
  global-config:
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    call-setters-on-nulls: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql